name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# This workflow runs on pushes and pull requests to the main branch, ensuring that code changes are tested before being merged.
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fjord-travel
    # The job checks out the code, sets up Node.js with caching for npm dependencies, installs dependencies, runs linting and type checking, and builds the Next.js application.
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Node.js with caching for npm dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22  # Use Node.js 22
        cache: 'npm'
        cache-dependency-path: './fjord-travel/package-lock.json' # Cache based on package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (Linting)
      run: npm run lint

    - name: Run TypeScript Typecheck
      run: npx tsc --noEmit

    - name: Build Next.js application
      run: npm run build